name: Deploy Website

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Configure AWS
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Setup node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build application
      - name: Build Application
        run: npm run build:prod

      # Deploy to S3
      - name: Deploy to S3
        run: aws s3 sync ./client/dist s3://${{ secrets.AWS_BUCKET_NAME }} --recursive

      # Create Cloudfront invalidation
      - name: Create Cloudfront Invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --path "/*"
